### ISSUE TITLE
[Setting] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by Naknakk** [Code-Drop-DevAcademy/2024-Team-12#5]
## 🛠 Issue

프로젝트 초기세팅을 합니다.

## 📝 To-do

- [x] 폴더링
- [x] 17.0 세팅, 아이폰 세로 & 라이트모드 고정
- [ ] 컬러 에셋 추가
- [ ] 디자인 에셋 추가
